# dataset:
#   name: FedISIC
#   csv_dir: ./data/FedISIC/splits/
#   data_root: ./data/FedISIC/FedISIC_npy/

dataset:
  csv_dir: ./data/FedPolyp/splits/FedPolyp_npy/
  data_root: ./data/FedPolyp/FedPolyp_npy/

initial_label_rate: 0.05
num_clients: 4
total_rounds: 100
al_period: 10
budget_per_round: 100
# label_budget_schedule: [40, 40, 60, 60, 80, 80, 100, 100]  # Optional: if you want varying budgets, comment out above line and uncomment this

local_epochs: 2
batch_size: 32
learning_rate: 0.0001
kl_weight: 0.005
annealing_step: 20

model:
  name: evidential_unet
  num_classes: 2  # Assuming binary mask (e.g., background vs. polyp)

seed: 42

uncertainty:
  beta: 0.5
  dirichlet_alpha: 1.0

sampling:
  use_cosine_filter: true

evidential_loss:
  lambda: 0.001

logo:
  num_clusters: 2